const fs = require('fs');
const path = require('path');
const assert = require('assert');
const sync = fs.readFileSync(path.join(__dirname, '..', 'src', 'sync.js'), 'utf8');
const organization = fs.readFileSync(path.join(__dirname, '..', 'src', 'organization.js'), 'utf8');
const platform = fs.readFileSync(path.join(__dirname, '..', 'src', 'platform_school_management.js'), 'utf8');
assert(sync.includes("app.post('/api/sync/device'"));
assert(sync.includes("app.post('/api/sync/push'"));
assert(sync.includes("app.post('/api/sync/pull'"));
assert(sync.includes("client_change_id"));
assert(sync.includes("sync_conflicts"));
assert(sync.includes("teacher_can_edit_exam_subject"));
assert(sync.includes("Teacher is not allowed to sync financial records"));
assert(sync.includes("Student is not enrolled in this class/session"));
assert(organization.includes("app.get('/api/public/school-config'"));
for (const token of ["app.post('/api/platform/schools'", 'await hashPassword(adminPassword)', 'mobile_app_configs', 'school_settings', 'branches']) assert(platform.includes(token));
assert(platform.includes("app.patch('/api/platform/schools/:id'"));
assert(platform.includes("app.get('/api/platform/schools/:id'"));
assert(platform.includes("app.post('/api/platform/schools/:id/logo'"));
console.log('ERP sync/tenant security contract checks: PASS');
