const fs = require('fs');
const path = require('path');
const assert = require('assert');

const client = fs.readFileSync(path.join(__dirname, '..', 'web', 'offline-sync.js'), 'utf8');
assert(client.includes("indexedDB.open(DB_NAME, DB_VERSION)"));
assert(client.includes("createObjectStore(OUTBOX"));
assert(client.includes("createObjectStore(CACHE"));
assert(client.includes("createObjectStore(META"));
assert(client.includes("function enqueue"));
assert(client.includes("async function cachePut"));
assert(client.includes("async function cacheGet"));
assert(client.includes("async function registerDevice"));
assert(client.includes("'/api/sync/device'"));
assert(client.includes("'/api/sync/changes?'"));
assert(client.includes("'/api/sync/push'"));
assert(client.includes("async function pull"));
assert(client.includes("async function sync"));
assert(client.includes("global.addEventListener('online'"));
assert(client.includes("navigator.onLine"));
assert(client.includes("conflicts"));
console.log('ERP web offline cache/pull/outbox contract checks: PASS');
