-- Anvi Mitra ERP: offline sync and access-control foundation.
CREATE TABLE IF NOT EXISTS sync_devices (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),school_id UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,device_key VARCHAR(200) NOT NULL,device_name VARCHAR(200),platform VARCHAR(30) NOT NULL DEFAULT 'unknown',last_cursor BIGINT NOT NULL DEFAULT 0,last_seen_at TIMESTAMPTZ,status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK(status IN('active','revoked')),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(school_id,device_key));
CREATE TABLE IF NOT EXISTS sync_changes (cursor BIGSERIAL PRIMARY KEY,school_id UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,device_id UUID REFERENCES sync_devices(id) ON DELETE SET NULL,client_change_id VARCHAR(200),base_cursor BIGINT NOT NULL DEFAULT 0,entity_type VARCHAR(100) NOT NULL,operation VARCHAR(50) NOT NULL DEFAULT 'upsert',payload JSONB NOT NULL DEFAULT '{}'::jsonb,entity_id UUID,changed_by UUID REFERENCES users(id) ON DELETE SET NULL,changed_at TIMESTAMPTZ NOT NULL DEFAULT now());
ALTER TABLE sync_changes ADD COLUMN IF NOT EXISTS operation VARCHAR(50) NOT NULL DEFAULT 'upsert';
ALTER TABLE sync_changes ADD COLUMN IF NOT EXISTS device_id UUID REFERENCES sync_devices(id) ON DELETE SET NULL;
ALTER TABLE sync_changes ADD COLUMN IF NOT EXISTS client_change_id VARCHAR(200);
ALTER TABLE sync_changes ADD COLUMN IF NOT EXISTS base_cursor BIGINT NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX IF NOT EXISTS sync_changes_device_client_idx ON sync_changes(school_id,device_id,client_change_id) WHERE client_change_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS sync_changes_school_cursor_idx ON sync_changes(school_id,cursor);
CREATE TABLE IF NOT EXISTS sync_conflicts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),school_id UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,device_id UUID REFERENCES sync_devices(id) ON DELETE SET NULL,entity_type VARCHAR(100) NOT NULL,entity_id UUID,local_payload JSONB NOT NULL DEFAULT '{}'::jsonb,server_payload JSONB NOT NULL DEFAULT '{}'::jsonb,resolution VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK(resolution IN('pending','server_wins','local_wins','merged')),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),resolved_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS sync_conflicts_school_status_idx ON sync_conflicts(school_id,resolution,created_at DESC);
CREATE TABLE IF NOT EXISTS local_storage_connectors (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),school_id UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,device_id UUID REFERENCES sync_devices(id) ON DELETE SET NULL,connector_type VARCHAR(30) NOT NULL DEFAULT 'desktop_folder' CHECK(connector_type IN('desktop_folder','nas_folder','external_drive')),display_name VARCHAR(200) NOT NULL,enabled BOOLEAN NOT NULL DEFAULT true,permission_mode VARCHAR(20) NOT NULL DEFAULT 'read_write' CHECK(permission_mode IN('read_only','read_write')),selected_path TEXT,last_sync_at TIMESTAMPTZ,last_error TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
